---
- hosts: "{{ selected_host}}"
  become: true
  become_user: root
  tasks:
  - name: See if reboot is required due to system maintenance
    stat: path=/var/run/reboot-required
    register: reboot_required_file

  - name: Reboot
    command: shutdown -r +1 "Rebooting for system maintenance"
    when: reboot_required_file.stat.exists == True
